name: Trigger Central Build
on:
  push:
    branches: [ main, resukisu, mksu, ksu ]
  workflow_dispatch:
    inputs:
      ksu_variant:
        description: 'Build Mode (resukisu / lkm / default)'
        required: false
        default: 'resukisu'
        type: choice
        options:
          - resukisu
          - lkm
          - default
      custom_localversion:
        description: 'Custom Localversion (defaults to Xiaomi stock format)'
        required: false
        default: '-android16-6-gb1493ec68d4a-abogki514973465-4k'
        type: string
jobs:
  trigger:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Trigger build in kernel-ci repository
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: MoeclubM/Kokuban_Kernel_CI_Center
          token: ${{ secrets.CI_TOKEN }}
          event-type: build-kernel
          client-payload: >-
            {
              "project": "mi17_sm8850",
              "branch": "${{ github.ref_name }}",
              "ksu_variant": "${{ inputs.ksu_variant || (github.ref_name == 'main' && 'resukisu' || github.ref_name) }}",
              "custom_localversion": "${{ inputs.custom_localversion || '-android16-6-gb1493ec68d4a-abogki514973465-4k' }}"
            }
